apiVersion: v1
kind: Service
metadata:
  name: adminer-web
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: adminer-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-web
spec:
  selector:
    matchLabels:
      app: adminer-web
  template:
    metadata:
      labels:
        app: adminer-web
    spec:
      containers:
        - name: web
          image: adminer:4.8.1-standalone
          args: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
          env:
          - name: ADMINER_DEFAULT_SERVER
            valueFrom:
              secretKeyRef:
                name: adminer-config
                key: ADMINER_DEFAULT_SERVER
          - name: ADMINER_DESIGN
            valueFrom:
              configMapKeyRef:
                name: adminer-config
                key: ADMINER_DESIGN
---
apiVersion: v1
data:
  ADMINER_DEFAULT_SERVER: Y2gwNC1sYWItZGI=
kind: Secret
metadata:
  name: adminer-config
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  ADMINER_DESIGN: price
kind: ConfigMap
metadata:
  name: adminer-config
  namespace: default

