apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ch10-lab.fullname" . }}-config
  labels:
    kiamol: ch10-lab
# ConfigController.Enabled should be parameterized
data:
  config.json: |-
    {
      "ConfigController": {
        "Enabled" : {{ .Values.configControllerEnabled }}
      }
    } 