apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ch10-lab.fullname" . }}
  labels:
    kiamol: ch10-lab
spec:
  selector:
    matchLabels:
      app: todo-web
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: todo-web
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: web
          image: kiamol/ch04-todo-list
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Test     # this should be parameterized
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "ch10-lab.fullname" . }}-config
